import React, { useState, useEffect, useRef } from 'react';
import { X, Loader2, Sparkles, Copy, Share2, Check } from 'lucide-react';
import { GoogleGenAI } from '@google/genai';
import { AssessmentReport } from '../types';

interface AssessmentModalProps {
  onClose: () => void;
}

export const AssessmentModal: React.FC<AssessmentModalProps> = ({ onClose }) => {
  const [step, setStep] = useState<'form' | 'loading' | 'result'>('form');
  const [formData, setFormData] = useState({
    grade: '8年级',
    rank: '中等 (前40%-60%)',
    issues: ''
  });
  const [currentReportId, setCurrentReportId] = useState<string | null>(null);
  const [reportHtml, setReportHtml] = useState('');
  const [copied, setCopied] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to top when step changes
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = 0;
    }
  }, [step]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStep('loading');

    try {
      const apiKey = process.env.API_KEY;
      if (!apiKey) {
        throw new Error('API Key not found');
      }

      const ai = new GoogleGenAI({ apiKey });
      
      const prompt = `
        你是一位幽默、风趣且极具鼓励性的顶级“学习战队教练”。你的沟通对象是初中生。
        请不要使用枯燥的说教语气，要像一个很酷的学长或者游戏教练一样说话。
        
        学生档案:
        - 年级: ${formData.grade}
        - 段位: ${formData.rank}
        - 遇到的BOSS(困扰): ${formData.issues}

        请完成以下任务:
        1. **判定战力层级**:
           - 基础区 (Base Zone): 需要补习惯和基础概念。
           - 提升区 (Improvement Zone): 需要攻克弱科和解题模型。
           - 巅峰区 (Peak Zone): 需要攻克压轴题和心态。
        2. **制定作战计划**: 给出3条具体的、符合脑科学的建议。每条建议都要包含“为什么这样做有效”。
        
        请直接输出一段 HTML 代码 (不要包含 \`\`\`html 标记，不要 markdown)，结构如下:
        
        <div class="space-y-4">
          <h3 class="text-2xl font-bold text-brand-700">战力评估: [层级名称] 🚀</h3>
          <p class="text-slate-600 bg-slate-50 p-4 rounded-xl">[用鼓励的语气简短分析现状，例如：听起来你遇到了瓶颈，但其实只要调整一下...]</p>
          
          <h4 class="text-xl font-bold text-slate-800 mt-6">专属通关攻略:</h4>
          <ul class="space-y-4">
             <li class="bg-white border border-slate-200 p-4 rounded-xl shadow-sm">
                <strong class="text-lg text-brand-600 block mb-1">🎮 攻略 1: [建议标题]</strong>
                <span class="text-slate-700">[建议内容，简单易懂]</span>
             </li>
             <li class="bg-white border border-slate-200 p-4 rounded-xl shadow-sm">
                <strong class="text-lg text-brand-600 block mb-1">🛡️ 攻略 2: [建议标题]</strong>
                <span class="text-slate-700">[建议内容]</span>
             </li>
             <li class="bg-white border border-slate-200 p-4 rounded-xl shadow-sm">
                <strong class="text-lg text-brand-600 block mb-1">⚡ 攻略 3: [建议标题]</strong>
                <span class="text-slate-700">[建议内容]</span>
             </li>
          </ul>
          <p class="text-sm text-slate-400 mt-4 text-center">记住：这只是当下的状态，你的潜力是无限的！保持行动！✨</p>
        </div>
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
      });

      const text = response.text || '<p>抱歉，服务器掉线了，请稍后重试。</p>';
      const cleanHtml = text.replace(/```html|```/g, '').trim();

      // Create Report Object
      const newReport: AssessmentReport = {
        id: Date.now().toString(),
        timestamp: Date.now(),
        grade: formData.grade,
        rank: formData.rank,
        issues: formData.issues,
        contentHtml: cleanHtml
      };

      // Save to localStorage list
      const existingReports: AssessmentReport[] = JSON.parse(localStorage.getItem('jhop_reports') || '[]');
      const updatedReports = [newReport, ...existingReports];
      localStorage.setItem('jhop_reports', JSON.stringify(updatedReports));

      setReportHtml(cleanHtml);
      setCurrentReportId(newReport.id);
      setStep('result');

    } catch (error) {
      console.error(error);
      setReportHtml('<p class="text-red-500">连接 AI 教练失败，请检查 API Key 配置。</p>');
      setStep('result');
    }
  };

  const getPlainText = () => {
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = reportHtml;
    // Basic formatting for better readability when pasted
    return `【JHOP 学习战力评估】\n\n${tempDiv.innerText}\n\nGenerated by JHOP System`;
  };

  const handleCopy = async () => {
    const text = getPlainText();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  const handleShare = async () => {
    const text = getPlainText();
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'JHOP 学习诊断报告',
          text: text,
        });
      } catch (err) {
        // User cancelled or share failed, do nothing specific
      }
    } else {
      // Fallback for browsers that don't support Web Share API
      handleCopy();
      alert('您的浏览器暂不支持直接分享，报告已自动复制到剪贴板。');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-brand-50">
          <h2 className="text-lg font-bold text-brand-800 flex items-center gap-2">
            <Sparkles className="w-5 h-5" />
            AI 战队教练诊断
          </h2>
          <button onClick={onClose} className="p-2 hover:bg-white rounded-full transition-colors text-slate-500">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div ref={scrollRef} className="p-6 overflow-y-auto scroll-smooth">
          {step === 'form' && (
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">你的年级</label>
                <select 
                  className="w-full p-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-brand-500 outline-none"
                  value={formData.grade}
                  onChange={e => setFormData({...formData, grade: e.target.value})}
                >
                  <option>7年级 (初一)</option>
                  <option>8年级 (初二)</option>
                  <option>9年级 (初三)</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">当前排位 / 状态</label>
                <select 
                  className="w-full p-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-brand-500 outline-none"
                  value={formData.rank}
                  onChange={e => setFormData({...formData, rank: e.target.value})}
                >
                  <option>新手/基础薄弱 (后30%)</option>
                  <option>进阶/中等水平 (前40%-60%)</option>
                  <option>高手/中上游 (前10%-30%)</option>
                  <option>大神/顶尖 (前5%)</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">最大的 BOSS (学习困扰) 是什么？</label>
                <textarea 
                  className="w-full p-3 rounded-xl border border-slate-200 focus:ring-2 focus:ring-brand-500 outline-none h-32 resize-none"
                  placeholder="比如：单词背了就忘、数学计算老出错、一考试就手抖..."
                  value={formData.issues}
                  onChange={e => setFormData({...formData, issues: e.target.value})}
                  required
                />
              </div>

              <div className="bg-blue-50 p-4 rounded-xl text-sm text-blue-700">
                <p>AI 教练将为你生成专属的“通关攻略”，并自动归档到你的复盘箱。</p>
              </div>

              <button 
                type="submit"
                className="w-full py-4 bg-brand-600 text-white font-bold rounded-xl hover:bg-brand-700 transition-colors shadow-lg shadow-brand-200"
              >
                生成诊断报告
              </button>
            </form>
          )}

          {step === 'loading' && (
            <div className="flex flex-col items-center justify-center py-12 space-y-4">
              <Loader2 className="w-12 h-12 text-brand-500 animate-spin" />
              <p className="text-slate-600 font-medium animate-pulse">正在分析战力数据...</p>
            </div>
          )}

          {step === 'result' && (
            <div className="space-y-6">
              <div 
                className="prose prose-brand max-w-none"
                dangerouslySetInnerHTML={{ __html: reportHtml }}
              />
              
              <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-slate-100">
                <button 
                  onClick={handleCopy}
                  className="flex-1 flex items-center justify-center gap-2 py-3 bg-white border border-slate-200 text-slate-700 font-medium rounded-xl hover:bg-slate-50 transition-colors"
                >
                  {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                  {copied ? '已复制' : '复制全文'}
                </button>
                <button 
                  onClick={handleShare}
                  className="flex-1 flex items-center justify-center gap-2 py-3 bg-white border border-slate-200 text-slate-700 font-medium rounded-xl hover:bg-slate-50 transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  分享报告
                </button>
              </div>

              <button 
                onClick={onClose}
                className="w-full py-3 bg-brand-600 text-white font-bold rounded-xl hover:bg-brand-700 transition-colors shadow-md"
              >
                保存并归队
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};