import React, { useState, useEffect } from 'react';
import { CheckCircle, Circle, Trophy, ClipboardList, Star, Lock, Calendar, History, X, Copy, Share2, Check, Trash2 } from 'lucide-react';
import { DEFAULT_TASKS, BADGES } from '../data';
import { DailyTask, AssessmentReport } from '../types';

interface DashboardProps {
  onOpenAssessment: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onOpenAssessment }) => {
  // Initialize tasks with error handling
  const [tasks, setTasks] = useState<DailyTask[]>(() => {
    try {
      const today = new Date().toDateString();
      const savedDate = localStorage.getItem('jhop_date');
      const savedTasks = localStorage.getItem('jhop_tasks');

      if (savedDate !== today) {
        localStorage.setItem('jhop_date', today);
        return DEFAULT_TASKS.map(t => ({ ...t, completed: false }));
      }
      
      return savedTasks ? JSON.parse(savedTasks) : DEFAULT_TASKS;
    } catch (e) {
      console.error("Error parsing tasks", e);
      return DEFAULT_TASKS;
    }
  });

  // Initialize points with safe parsing
  const [points, setPoints] = useState(() => {
    try {
      return parseInt(localStorage.getItem('jhop_points') || '0');
    } catch (e) {
      return 0;
    }
  });

  // Initialize reports
  const [reports, setReports] = useState<AssessmentReport[]>([]);
  const [selectedReport, setSelectedReport] = useState<AssessmentReport | null>(null);
  const [copied, setCopied] = useState(false);

  // Persistence
  useEffect(() => {
    localStorage.setItem('jhop_tasks', JSON.stringify(tasks));
  }, [tasks]);

  useEffect(() => {
    localStorage.setItem('jhop_points', points.toString());
  }, [points]);

  // Load reports on mount
  useEffect(() => {
    const savedReports = localStorage.getItem('jhop_reports');
    if (savedReports) {
      try {
        setReports(JSON.parse(savedReports));
      } catch (e) {
        console.error("Failed to parse reports", e);
        // If data is corrupted, reset it to prevent crash loops
        localStorage.setItem('jhop_reports', '[]');
      }
    }
  }, [onOpenAssessment]);

  const toggleTask = (id: string) => {
    const task = tasks.find(t => t.id === id);
    if (!task) return;

    const isCompleting = !task.completed;
    const newTasks = tasks.map(t => t.id === id ? { ...t, completed: isCompleting } : t);
    setTasks(newTasks);
    const pointChange = isCompleting ? 10 : -10;
    setPoints(prev => Math.max(0, prev + pointChange));
  };

  const deleteReport = (id: string) => {
    if (window.confirm('确定要删除这份诊断报告吗？')) {
      const updatedReports = reports.filter(r => r.id !== id);
      setReports(updatedReports);
      localStorage.setItem('jhop_reports', JSON.stringify(updatedReports));
      setSelectedReport(null);
    }
  };

  const completedCount = tasks.filter(t => t.completed).length;
  const progress = Math.round((completedCount / tasks.length) * 100);

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  };

  const getPlainText = (report: AssessmentReport) => {
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = report.contentHtml;
    return `【JHOP 历史复盘: ${formatDate(report.timestamp)}】\n\n困扰: ${report.issues}\n\n${tempDiv.innerText}\n\nGenerated by JHOP System`;
  };

  const handleCopy = async (report: AssessmentReport) => {
    const text = getPlainText(report);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  const handleShare = async (report: AssessmentReport) => {
    const text = getPlainText(report);
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'JHOP 学习诊断复盘',
          text: text,
        });
      } catch (err) {
        // User cancelled
      }
    } else {
      handleCopy(report);
      alert('您的浏览器暂不支持直接分享，报告已自动复制到剪贴板。');
    }
  };

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-8 animate-fade-in relative">
      
      {/* Welcome & Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 bg-gradient-to-r from-brand-600 to-brand-500 rounded-2xl p-6 text-white shadow-lg relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Trophy className="w-32 h-32" />
          </div>

          <div className="relative z-10">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h2 className="text-2xl font-bold">今日状态调优</h2>
                <p className="text-brand-100 text-sm mt-1">坚持就是胜利，你已经获得了 <span className="font-bold text-yellow-300 text-lg">{points}</span> 能量值！</p>
              </div>
              <div className="text-right">
                <div className="text-3xl font-bold">{progress}%</div>
                <div className="text-xs text-brand-100 opacity-80">今日完成度</div>
              </div>
            </div>
            
            <div className="w-full bg-brand-800/40 rounded-full h-3 mb-2">
              <div 
                className="bg-white rounded-full h-3 transition-all duration-500 shadow-[0_0_10px_rgba(255,255,255,0.5)]" 
                style={{ width: `${progress}%` }}
              ></div>
            </div>
          </div>
        </div>

        <div 
          onClick={onOpenAssessment}
          className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 hover:shadow-md transition-all cursor-pointer group hover:-translate-y-1"
        >
          <div className="flex items-start justify-between mb-4">
            <div className="p-3 bg-accent-50 rounded-xl text-accent-600 group-hover:bg-accent-100 transition-colors">
              <ClipboardList className="w-6 h-6" />
            </div>
            <div className="text-right">
               <span className="text-2xl font-bold text-slate-800">{reports.length}</span>
               <span className="text-xs text-slate-400 block">累计诊断</span>
            </div>
          </div>
          <h3 className="text-lg font-bold text-slate-800">AI 学习诊断</h3>
          <p className="text-sm text-slate-500 mt-1">开启新一轮的战力评估。</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Tasks */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
          <h3 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-yellow-100 text-yellow-600">
              <Star className="w-5 h-5 fill-current" />
            </span>
            每日必做清单 (+10分/个)
          </h3>
          <div className="space-y-3">
            {tasks.map(task => (
              <div 
                key={task.id} 
                onClick={() => toggleTask(task.id)}
                className={`flex items-center gap-4 p-4 rounded-xl cursor-pointer transition-all border group ${
                  task.completed 
                    ? 'bg-slate-50 border-slate-200 opacity-75' 
                    : 'bg-white border-slate-100 hover:border-brand-300 hover:shadow-sm hover:scale-[1.01]'
                }`}
              >
                <div className={`flex-shrink-0 transition-all duration-300 ${task.completed ? 'text-green-500 scale-110' : 'text-slate-300 group-hover:text-brand-400'}`}>
                  {task.completed ? <CheckCircle className="w-6 h-6" /> : <Circle className="w-6 h-6" />}
                </div>
                <span className={`text-lg transition-all ${task.completed ? 'text-slate-400 line-through' : 'text-slate-700 font-medium'}`}>
                  {task.text}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Badges */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 flex flex-col">
          <div className="mb-6 flex justify-between items-center">
             <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <span className="flex items-center justify-center w-8 h-8 rounded-full bg-indigo-100 text-indigo-600">
                <Trophy className="w-5 h-5 fill-current" />
              </span>
              成就勋章墙
            </h3>
            <span className="text-xs font-bold bg-slate-100 text-slate-600 px-2 py-1 rounded-full">
              能量: {points}
            </span>
          </div>
          <div className="grid grid-cols-3 gap-3 flex-grow content-start">
            {BADGES.map(badge => {
              const isUnlocked = points >= badge.threshold;
              return (
                <div 
                  key={badge.id} 
                  className={`relative p-2 rounded-xl border transition-all duration-300 flex flex-col items-center text-center gap-1 ${
                    isUnlocked 
                      ? 'bg-gradient-to-br from-white to-slate-50 border-slate-200 shadow-sm' 
                      : 'bg-slate-50 border-slate-100 opacity-60 grayscale'
                  }`}
                >
                  <div className={`p-2 rounded-full ${isUnlocked ? 'bg-white shadow-md' : 'bg-slate-200'}`}>
                    <badge.icon className={`w-6 h-6 ${isUnlocked ? badge.color : 'text-slate-400'}`} />
                  </div>
                  <h4 className={`text-xs font-bold ${isUnlocked ? 'text-slate-800' : 'text-slate-500'}`}>{badge.name}</h4>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Reports Archive */}
      <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
        <h3 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
          <History className="w-6 h-6 text-brand-500" />
          诊断档案室 (复盘箱)
        </h3>
        
        {reports.length === 0 ? (
          <div className="text-center py-8 text-slate-400 bg-slate-50 rounded-xl border border-dashed border-slate-200">
            暂无诊断记录。点击右上角“AI 学习诊断”开始第一次评估吧！
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {reports.map((report) => (
              <div 
                key={report.id}
                onClick={() => setSelectedReport(report)}
                className="bg-slate-50 border border-slate-200 p-4 rounded-xl cursor-pointer hover:shadow-md hover:border-brand-300 transition-all group relative"
              >
                <div className="flex justify-between items-start mb-2">
                  <span className="text-xs font-bold text-brand-600 bg-brand-100 px-2 py-0.5 rounded-full">
                    {report.grade}
                  </span>
                  <span className="text-xs text-slate-400 flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    {formatDate(report.timestamp)}
                  </span>
                </div>
                <h4 className="font-bold text-slate-800 mb-1 group-hover:text-brand-700 truncate">{report.rank}</h4>
                <p className="text-xs text-slate-500 line-clamp-2">困扰: {report.issues}</p>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Report Detail Modal */}
      {selectedReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in" onClick={() => setSelectedReport(null)}>
          <div 
            className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] animate-slide-up"
            onClick={e => e.stopPropagation()}
          >
            <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-brand-50">
              <div>
                <h2 className="text-lg font-bold text-brand-800">历史诊断档案</h2>
                <p className="text-xs text-brand-600">{formatDate(selectedReport.timestamp)} | {selectedReport.grade}</p>
              </div>
              
              <div className="flex items-center gap-2">
                <button 
                  onClick={() => deleteReport(selectedReport.id)}
                  className="p-2 hover:bg-red-50 text-slate-400 hover:text-red-500 rounded-full transition-colors"
                  title="删除此报告"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
                <div className="w-px h-4 bg-slate-200 mx-1"></div>
                <button onClick={() => setSelectedReport(null)} className="p-2 hover:bg-white rounded-full transition-colors text-slate-500">
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>
            
            <div className="p-6 overflow-y-auto">
               <div className="mb-4 bg-slate-50 p-4 rounded-xl border border-slate-100">
                 <strong className="text-sm text-slate-500 block mb-1">当时困扰:</strong>
                 <p className="text-slate-800">{selectedReport.issues}</p>
               </div>
               <div 
                className="prose prose-brand max-w-none"
                dangerouslySetInnerHTML={{ __html: selectedReport.contentHtml }}
              />

              <div className="flex flex-col sm:flex-row gap-3 pt-6 mt-6 border-t border-slate-100">
                <button 
                  onClick={() => handleCopy(selectedReport)}
                  className="flex-1 flex items-center justify-center gap-2 py-3 bg-white border border-slate-200 text-slate-700 font-medium rounded-xl hover:bg-slate-50 transition-colors"
                >
                  {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                  {copied ? '已复制' : '复制全文'}
                </button>
                <button 
                  onClick={() => handleShare(selectedReport)}
                  className="flex-1 flex items-center justify-center gap-2 py-3 bg-white border border-slate-200 text-slate-700 font-medium rounded-xl hover:bg-slate-50 transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  分享报告
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};